
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://hakim:admin123@db:5432/fadhlan_hakim
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db-uas
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hakim
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fadhlan_hakim
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: